knitr::opts_chunk$set(echo = F)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(RColorBrewer)
library(plotly)
library(limma)
library(qvalue)
library(tidyverse)
library(gridExtra)
library(ggrepel)
library(gplots)
library(knitr)
library(piano)
library(conflicted)
library(mixOmics)
library(clusterProfiler)
library(AnnotationHub)
library(org.Hs.eg.db)
library(VennDiagram)
library(eulerr)
theme_set(theme_bw(base_size = 18))
mycolors <- c("Blue", "Red", "Gray")
names(mycolors) <- c("Blue", "Red", "Gray")

conflict_prefer("summarize", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("mutate", "dplyr")
conflict_prefer("arrange", "dplyr")

candidates <- function(df){
  df$minuslogqval <- -1*log10(df$Qvalue)
  df$Color <- ifelse(df$AVG.Log2.Ratio >= 0.58 & df$Qvalue < 0.01, "Red", "Grey")
  df$Color <- ifelse(df$AVG.Log2.Ratio <= -0.58 & df$Qvalue < 0.01, "Blue", df$Color)
  #df$Label <- NA
  return(df)
}